### ISSUE TITLE
Allow custom config

### ISSUE THREAD

**Issue by ihavenoface** [tguillem/android-ampd#1]
I would like to add an audiostream to the config but the app simply overwrites the file when starting mpd.
Any chance of seeing some option for own, additional config?

**Comment by tguillem** [comment]
I stopped the development and support of ampd. Instead I did an other fork in top of more recent commits of mpd. With this fork, you can put your own mpd.conf in /sdcard/mpd.conf. If there is a feature or a lib missing, you can easily add it in android/build.py.
I'm waiting my commits to be merged upstream. In the meantime, you can check here https://github.com/tguillem/mpd/tree/android-nfs there is an apk in the release page.
