### ISSUE TITLE
problem with online radio stream

### ISSUE THREAD

**Issue by gmircea** [tguillem/android-ampd#4]
I installed ampd on my mobile and set up a directory with mp3 files, and also with some online radio playlist files (m3u + pls)
I am able to connect using a client from my pc and play the mp3 files fine.
But I also want to listen to online radios and I'm having trouble with the playlist files, they won't play:
the client discovers the playlists, but when trying to play an entry it just advances to the next one and so on...
The playlist files are downloaded from online radio providers, e.g skyfm
I've attached some files to this email.
I've also set up mpd on my linux machine and using the same playlist files everything works.
When trying to play I've found this entry in logcat:
W/mpd(17782): decoder_thread: curl failed: Failed connect to <ip_address_of_online_radio>; Operation now in progress

See sample playlist used: https://gist.github.com/gitmester/c0cd20e4e5f80a79ce64#file-sky-fm-smooth-lounge_old-pls

**Comment by tguillem** [comment]
I stopped the development and support of ampd. Instead I did an other fork in top of more recent commits of mpd. With this fork, you can put your own mpd.conf in /sdcard/mpd.conf. If there is a feature or a lib missing, you can easily add it in android/build.py.
I'm waiting my commits to be merged upstream. In the meantime, you can check here https://github.com/tguillem/mpd/tree/android-nfs there is an apk in the release page.
