### ISSUE TITLE
Opus support?

### ISSUE THREAD

**Issue by C0DEHERO** [tguillem/android-ampd#6]
The current version of MPD has opus support, but I found out that ampd does not. Is it possible to add opus support to ampd?

**Comment by tguillem** [comment]
I stopped old android-ampd support to start over one sane new mpd version.

Here is some of my work that is still not merged in mpd: https://github.com/tguillem/mpd/commits/android

**Comment by C0DEHERO** [comment]
Oh! That's cool. I'm going to check this out. Thank you :)
