### ISSUE TITLE
Add support for httpd output?

### ISSUE THREAD

**Issue by honglu-intel** [tguillem/android-ampd#7]
It seems the library does not support httpd plugin as it is right now?

I checked out the project and added the httpd ouput to the config file and the daemon fails to start due to lack of httpd support.

It would be really convenient to add streaming functionality for android TV box which is a new option for low power media server.

**Comment by tguillem** [comment]
Hello,

I stopped the development and support of ampd. Instead I did an other
fork in top of more recent commits of mpd. With this fork, you can put
your own mpd.conf in /sdcard/mpd.conf. If there is a feature or a lib
missing, you can easily add it in android/build.py. I'm waiting my
commits to be merged upstream. In the meantime, you can check here
https://github.com/tguillem/mpd/tree/android-nfs there is an apk in the
release page.

Thomas Guillem

On Tue, May 26, 2015, at 05:33, blueSky wrote:
> It seems the library does not support httpd plugin as it is right now?


> I checked out the project and added the httpd ouput to the config file
> and the daemon fails to start due to lack of httpd support.


> It would be really convenient to add streaming functionality for
> android TV box which is a new option for low power media server.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/tguillem/android-ampd/issues/7

**Comment by honglu-intel** [comment]
Great work! I will definitely check that out.

Hong
